postgers_db:
  image: postgres:latest
  environment:
    POSTGRES_USER : linkup
    POSTGRES_PASSWORD: secret
    POSTGRES_DATABASE: simpwill
  ports:
    - "5432:5432"

mailhog:
  image: mailhog/mailhog
  ports:
    - "1025:1025"
    - "8025:8025"

minio:
  image: minio/minio
  ports:
    - "9000:9000"
  volumes:
    - ./storage/app:/data
  environment:
    MINIO_ACCESS_KEY: minio_access_key
    MINIO_ACCESS_KEY_ID: minio_access_key
    MINIO_SECRET_KEY: minio_secret_key
    MINIO_REGION_NAME: "us-east-1"
  command: server /data
